---
- name: install_base_soft | include OS-specific variables.
  ansible.builtin.include_vars: "{{ ansible_os_family }}.yml"

- name: install_base_soft | update facts.
  ansible.builtin.set_fact:
    base_soft_list: "{{ __base_soft_list }}"

- name: install_base_soft | update apt cache.
  ansible.builtin.apt:
    update_cache: true
    cache_valid_time: 86400
  when: ansible_os_family == 'Debian'

- name: install_base_soft | install required packages.
  ansible.builtin.apt:
    name: "{{ base_soft_list }}"
    update_cache: false
  when: ansible_os_family == 'Debian'

- name: install_base_soft | install extra packages.
  ansible.builtin.apt:
    name: "{{ base_soft_list_extra }}"
    update_cache: false
  when: ansible_os_family == 'Debian'
