---
- name: install_base_soft | include OS-specific variables.
  ansible.builtin.include_vars: RedHat.yml

- name: install_base_soft | update facts epel_repo_url.
  ansible.builtin.set_fact:
    epel_repo_url: "{{ __epel_repo_url }}"

- name: install_base_soft | update facts epel_repo_gpg_key_url.
  ansible.builtin.set_fact:
    epel_repo_gpg_key_url: "{{ __epel_repo_gpg_key_url }}"

- name: install_base_soft | update facts epel_repofile_path.
  ansible.builtin.set_fact:
    epel_repofile_path: "{{ __epel_repofile_path }}"

- name: install_base_soft | check if EPEL repo is already configured.
  ansible.builtin.stat:
    path: "{{ epel_repofile_path }}"
  register: epel_repofile_result

- name: install_base_soft | import EPEL GPG key.
  ansible.builtin.rpm_key:
    key: "{{ epel_repo_gpg_key_url }}"
    state: present
  register: result
  until: result is succeeded
  retries: 5
  delay: 10
  when: not epel_repofile_result.stat.exists
  ignore_errors: "{{ ansible_check_mode }}"

- name: install_base_soft | install EPEL repo.
  ansible.builtin.yum:
    name: "{{ epel_repo_url }}"
    state: present
  register: result
  until: result is succeeded
  retries: 5
  delay: 10
  when: not epel_repofile_result.stat.exists
